import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "../styles/home.module.scss";
import ThemeToggle from "../components/ThemeToggle/ThemeToggle";
import NewDock from "@/components/NewDock/NewDock";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Kuldeepsinh Jadeja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeToggle />
      <main className={`${styles.main} ${geistSans.variable} ${geistMono.variable}`}>
        {/* <h1 className={styles.title}>Welcome to My Portfolio</h1>
        <p className={styles.description}>
          Hello! I'm Kuldeepsinh Jadeja, a passionate developer.
        </p> */}
        {/* <Dock /> */}
        <NewDock />
      </main>

    </>
  );
}
